//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_vrsketch : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean TransformCanvasButton
        {
            get
            {
                return SteamVR_Actions.vrsketch_TransformCanvasButton;
            }
        }
        
        public virtual SteamVR_Action_Single DrawTrigger
        {
            get
            {
                return SteamVR_Actions.vrsketch_DrawTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean ZoomCanvasButton
        {
            get
            {
                return SteamVR_Actions.vrsketch_ZoomCanvasButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean AddPatchButton
        {
            get
            {
                return SteamVR_Actions.vrsketch_AddPatchButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean DeleteButton
        {
            get
            {
                return SteamVR_Actions.vrsketch_DeleteButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean GridStateButton
        {
            get
            {
                return SteamVR_Actions.vrsketch_GridStateButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean StudyNextAction
        {
            get
            {
                return SteamVR_Actions.vrsketch_StudyNextAction;
            }
        }
        
        public virtual SteamVR_Action_Boolean MirrorStateButton
        {
            get
            {
                return SteamVR_Actions.vrsketch_MirrorStateButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean SwitchSystemButton
        {
            get
            {
                return SteamVR_Actions.vrsketch_SwitchSystemButton;
            }
        }
    }
}
